// Format
// name: name of the file or folder
// type: folder or file
// value: number of bytes of the doc (calculated at folder level by d3)
// children: sub files or sub folders

export const data = {
  name: "minutes",
  children: [
    {
      name: "Community Benefits Advisory Committee Regular Meeting",
      children: [
      {'name': 'Central Square', 'value': 1}
      ]
      },
      {
      name: "Economic Development & University Relations Committee Committee Meetings",
      children: [
      {'name': 'Central Square', 'value': 1},
      {'name': 'Brewer Street', 'value': 1},
      {'name': 'Fuller Place', 'value': 1},
      {'name': 'Putnam Avenue', 'value': 1},
      {'name': 'Hampshire Street', 'value': 1},
      {'name': 'Porter Square', 'value': 1},
      {'name': 'Prospect Street', 'value': 1}
      ]
      },
      {
      name: "City Council Special Meeting",
      children: [
      {'name': 'Central Square', 'value': 3},
      {'name': 'Massachusetts Avenue', 'value': 3},
      {'name': 'Memorial Drive', 'value': 3},
      {'name': 'Brattle Street', 'value': 2},
      {'name': 'Broadway', 'value': 2},
      {'name': 'Church Street', 'value': 2},
      {'name': 'Dana Street', 'value': 2},
      {'name': 'Fuller Place', 'value': 2},
      {'name': 'Harvard Square', 'value': 2},
      {'name': 'Harvard Street', 'value': 2},
      {'name': 'Irving Street', 'value': 2},
      {'name': 'Main Street', 'value': 2},
      {'name': 'Porter Square', 'value': 2},
      {'name': 'Alewife Brook Parkway', 'value': 2},
      {'name': 'Antrim Street', 'value': 2},
      {'name': 'Beech Street', 'value': 2},
      {'name': 'Cambridge Street', 'value': 2},
      {'name': 'Chestnut Street', 'value': 2},
      {'name': 'Dunster Street', 'value': 2},
      {'name': 'Eustis Street', 'value': 2},
      {'name': 'Hampshire Street', 'value': 2},
      {'name': 'Norfolk Street', 'value': 2},
      {'name': 'Oak Street', 'value': 2},
      {'name': 'Pine Street', 'value': 2},
      {'name': 'Roseland Street', 'value': 2},
      {'name': 'Upton Street', 'value': 2},
      {'name': 'Vassal Lane', 'value': 2},
      {'name': 'Arrow Street', 'value': 1},
      {'name': 'Ash Street', 'value': 1},
      {'name': 'Bow Street', 'value': 1},
      {'name': 'Brewer Street', 'value': 1},
      {'name': 'Mount Auburn Street', 'value': 1},
      {'name': '5th Street', 'value': 1},
      {'name': 'Albany Street', 'value': 1},
      {'name': 'Alewife Brook Pkwy', 'value': 1},
      {'name': 'Alpine Street', 'value': 1},
      {'name': 'Amory Street', 'value': 1},
      {'name': 'Arlington Street', 'value': 1},
      {'name': 'Austin Park', 'value': 1},
      {'name': 'Berkeley Street', 'value': 1},
      {'name': 'Brown Street', 'value': 1},
      {'name': 'Clark Street', 'value': 1},
      {'name': 'Concord Avenue', 'value': 1},
      {'name': 'Creighton Street', 'value': 1},
      {'name': 'Dudley Street', 'value': 1},
      {'name': 'Earhart Street', 'value': 1},
      {'name': 'Eaton Street', 'value': 1},
      {'name': 'Elm Street', 'value': 1},
      {'name': 'Fayerweather Street', 'value': 1},
      {'name': 'Fayette Street', 'value': 1},
      {'name': 'Field Street', 'value': 1},
      {'name': 'Follen Street', 'value': 1},
      {'name': 'Foster Street', 'value': 1},
      {'name': 'Fresh Pond Pkwy', 'value': 1},
      {'name': 'Garden Street', 'value': 1},
      {'name': 'Gerry Street', 'value': 1},
      {'name': 'Hamilton Street', 'value': 1},
      {'name': 'Hancock Street', 'value': 1},
      {'name': 'Hayes Street', 'value': 1},
      {'name': 'High Street', 'value': 1},
      {'name': 'Huron Avenue', 'value': 1},
      {'name': 'Inman Street', 'value': 1},
      {'name': 'Jay Street', 'value': 1},
      {'name': 'Kendall Square', 'value': 1},
      {'name': 'Lambert Street', 'value': 1},
      {'name': 'Larchwood Drive', 'value': 1},
      {'name': 'Lawn Street', 'value': 1},
      {'name': 'Lee Street', 'value': 1},
      {'name': 'Lexington Avenue', 'value': 1},
      {'name': 'Mason Street', 'value': 1},
      {'name': 'Milton Street', 'value': 1},
      {'name': 'Parker Street', 'value': 1},
      {'name': 'Plympton Street', 'value': 1},
      {'name': 'Porter Road', 'value': 1},
      {'name': 'Prospect Street', 'value': 1},
      {'name': 'Quincy Street', 'value': 1},
      {'name': 'River Street', 'value': 1},
      {'name': 'Riverside Place', 'value': 1},
      {'name': 'Roberts Road', 'value': 1},
      {'name': 'Russell Street', 'value': 1},
      {'name': 'Salem Street', 'value': 1},
      {'name': 'Soden Place', 'value': 1},
      {'name': 'Upland Road', 'value': 1},
      {'name': 'Walden Street', 'value': 1},
      {'name': 'Waterhouse Street', 'value': 1},
      {'name': 'Watson Street', 'value': 1},
      {'name': 'White Street', 'value': 1},
      {'name': 'Willard Street', 'value': 1},
      {'name': 'Acorn Park', 'value': 1},
      {'name': 'Acorn Park Drive', 'value': 1},
      {'name': 'Alewife Red Line', 'value': 1},
      {'name': 'Berkshire Street', 'value': 1},
      {'name': 'Bigelow Street', 'value': 1},
      {'name': 'Churchill Avenue', 'value': 1},
      {'name': 'Corporal Burns Road', 'value': 1},
      {'name': 'Cottage Street', 'value': 1},
      {'name': 'Dover Street', 'value': 1},
      {'name': 'Dudley Court', 'value': 1},
      {'name': 'Education Street', 'value': 1},
      {'name': 'Fawcett Street', 'value': 1},
      {'name': 'Fenno Street', 'value': 1},
      {'name': 'Forest Street', 'value': 1},
      {'name': 'Franklin Street', 'value': 1},
      {'name': 'Green Street', 'value': 1},
      {'name': 'Harvard Yard', 'value': 1},
      {'name': 'Hurley Street', 'value': 1},
      {'name': 'Jackson Place', 'value': 1},
      {'name': 'Jackson Street', 'value': 1},
      {'name': 'Jefferson Park', 'value': 1},
      {'name': 'Land Boulevard', 'value': 1},
      {'name': 'Laurel Street', 'value': 1},
      {'name': 'Madison Avenue', 'value': 1},
      {'name': 'Mass Avenue', 'value': 1},
      {'name': 'Montgomery Street', 'value': 1},
      {'name': 'Oxford Street', 'value': 1},
      {'name': 'Reed Street', 'value': 1},
      {'name': 'Rindge Avenue', 'value': 1},
      {'name': 'Spring Street', 'value': 1},
      {'name': 'Third Street', 'value': 1},
      {'name': 'Thorndike Street', 'value': 1},
      {'name': 'Winter Street', 'value': 1}
      ]
      },
      {
      name: "City Council Regular Meeting",
      children: [
      {'name': 'Beech Street', 'value': 32},
      {'name': 'Central Square', 'value': 32},
      {'name': 'Roseland Street', 'value': 32},
      {'name': 'Massachusetts Avenue', 'value': 30},
      {'name': 'Memorial Drive', 'value': 23},
      {'name': 'Upton Street', 'value': 22},
      {'name': 'Cambridge Street', 'value': 21},
      {'name': 'Broadway', 'value': 20},
      {'name': 'Concord Avenue', 'value': 20},
      {'name': 'Garden Street', 'value': 19},
      {'name': 'Hampshire Street', 'value': 19},
      {'name': 'Huron Avenue', 'value': 18},
      {'name': 'Eustis Street', 'value': 17},
      {'name': 'Alewife Brook Parkway', 'value': 16},
      {'name': 'Church Street', 'value': 15},
      {'name': 'Dunster Street', 'value': 15},
      {'name': 'Inman Street', 'value': 15},
      {'name': 'Plympton Street', 'value': 15},
      {'name': 'Dudley Street', 'value': 14},
      {'name': 'Porter Square', 'value': 14},
      {'name': 'Amory Street', 'value': 13},
      {'name': 'Berkeley Street', 'value': 13},
      {'name': 'Follen Street', 'value': 13},
      {'name': 'Harvard Square', 'value': 13},
      {'name': 'Main Street', 'value': 13},
      {'name': 'Mason Street', 'value': 13},
      {'name': 'Oak Street', 'value': 13},
      {'name': 'Quincy Street', 'value': 13},
      {'name': 'Waterhouse Street', 'value': 13},
      {'name': 'Kendall Square', 'value': 11},
      {'name': 'Walden Street', 'value': 11},
      {'name': 'Raymond Street', 'value': 10},
      {'name': 'Brattle Street', 'value': 9},
      {'name': 'River Street', 'value': 9},
      {'name': 'Vassal Lane', 'value': 9},
      {'name': 'Western Avenue', 'value': 9},
      {'name': 'Richdale Avenue', 'value': 8},
      {'name': 'Binney Street', 'value': 8},
      {'name': 'Sidney Street', 'value': 7},
      {'name': 'Pleasant Street', 'value': 7},
      {'name': 'Inman Square', 'value': 7},
      {'name': 'Gore Street', 'value': 7},
      {'name': 'Rindge Avenue', 'value': 7},
      {'name': 'Concord Ave', 'value': 7},
      {'name': 'Harvard Street', 'value': 7},
      {'name': 'Norfolk Street', 'value': 7},
      {'name': 'Hurley Street', 'value': 6},
      {'name': 'Jackson Place', 'value': 6},
      {'name': 'Windsor Street', 'value': 6},
      {'name': 'Columbia Street', 'value': 6},
      {'name': 'Cambridge Center', 'value': 6},
      {'name': 'Churchill Avenue', 'value': 6},
      {'name': 'Jfk Street', 'value': 6},
      {'name': 'Prospect Street', 'value': 6},
      {'name': 'Creighton Street', 'value': 5},
      {'name': 'Erie Street', 'value': 5},
      {'name': 'Pine Street', 'value': 5},
      {'name': 'Ames Street', 'value': 5},
      {'name': 'Berkshire Street', 'value': 5},
      {'name': 'Bishop Allen Drive', 'value': 5},
      {'name': 'Mount Auburn Street', 'value': 5},
      {'name': 'Elm Street', 'value': 4},
      {'name': 'Brewer Street', 'value': 4},
      {'name': 'Jefferson Park', 'value': 4},
      {'name': 'Porter Road', 'value': 4},
      {'name': 'Upland Road', 'value': 4},
      {'name': 'Cherry Street', 'value': 4},
      {'name': 'Market Street', 'value': 4},
      {'name': 'Otis Street', 'value': 4},
      {'name': 'School Street', 'value': 4},
      {'name': 'Lexington Avenue', 'value': 4},
      {'name': 'Cedar Street', 'value': 4},
      {'name': 'Frost Terrace', 'value': 4},
      {'name': 'Spring Street', 'value': 4},
      {'name': 'Fulkerson Street', 'value': 4},
      {'name': 'Saville Street', 'value': 4},
      {'name': 'Fayette Street', 'value': 4},
      {'name': 'Acorn Park', 'value': 4},
      {'name': 'Acorn Park Drive', 'value': 4},
      {'name': 'Pearl Street', 'value': 4},
      {'name': 'Winter Street', 'value': 4},
      {'name': 'Antrim Street', 'value': 4},
      {'name': 'Auburn Street', 'value': 4},
      {'name': 'Dana Street', 'value': 4},
      {'name': 'Magazine Street', 'value': 4},
      {'name': 'Mass Avenue', 'value': 4},
      {'name': 'New Street', 'value': 4},
      {'name': 'Green Street', 'value': 4},
      {'name': 'Cambridge Park Drive', 'value': 3},
      {'name': 'Cottage Street', 'value': 3},
      {'name': 'Regent Street', 'value': 3},
      {'name': 'Corporal Burns Road', 'value': 3},
      {'name': 'Richdale Ave', 'value': 3},
      {'name': 'Rogers Street', 'value': 3},
      {'name': 'Blackstone Street', 'value': 3},
      {'name': 'Brattle Square', 'value': 3},
      {'name': 'Eliot Street', 'value': 3},
      {'name': 'Franklin Street', 'value': 3},
      {'name': 'Winthrop Street', 'value': 3},
      {'name': 'Field Street', 'value': 3},
      {'name': 'King Open', 'value': 3},
      {'name': 'Oxford Street', 'value': 3},
      {'name': 'Story Street', 'value': 3},
      {'name': 'Bristol Street', 'value': 3},
      {'name': 'Fuller Place', 'value': 3},
      {'name': 'Hancock Street', 'value': 3},
      {'name': 'Plymouth Street', 'value': 3},
      {'name': 'Thorndike Street', 'value': 3},
      {'name': 'Allston Street', 'value': 3},
      {'name': 'Mt. Auburn Street', 'value': 3},
      {'name': 'Portland Street', 'value': 3},
      {'name': 'Bow Street', 'value': 3},
      {'name': 'Chestnut Street', 'value': 2},
      {'name': 'East Street', 'value': 2},
      {'name': 'Fresh Pond Pkwy', 'value': 2},
      {'name': 'Gold Star Road', 'value': 2},
      {'name': 'Washington Street', 'value': 2},
      {'name': 'Cherry St', 'value': 2},
      {'name': 'Kennedy Street', 'value': 2},
      {'name': 'Sciarappa Street', 'value': 2},
      {'name': '5th Street', 'value': 2},
      {'name': 'Pearl St', 'value': 2},
      {'name': 'Brookline Street', 'value': 2},
      {'name': 'Line Street', 'value': 2},
      {'name': 'Arlington Street', 'value': 2},
      {'name': 'Norris Street', 'value': 2},
      {'name': 'Pemberton Street', 'value': 2},
      {'name': 'Canal Park', 'value': 2},
      {'name': 'Holyoke Street', 'value': 2},
      {'name': 'Larch Road', 'value': 2},
      {'name': 'Longfellow Park', 'value': 2},
      {'name': 'Maple Avenue', 'value': 2},
      {'name': 'Pacific Street', 'value': 2},
      {'name': 'Quincy Square', 'value': 2},
      {'name': 'State Street', 'value': 2},
      {'name': 'Fayerweather Street', 'value': 2},
      {'name': 'Harvey Street', 'value': 2},
      {'name': 'Parker Street', 'value': 2},
      {'name': 'Woodrow Wilson Court', 'value': 2},
      {'name': 'Newport Road', 'value': 2},
      {'name': 'Sacramento Street', 'value': 2},
      {'name': 'Alpine Street', 'value': 2},
      {'name': 'Charles Street', 'value': 2},
      {'name': 'Earhart Street', 'value': 2},
      {'name': 'Eaton Street', 'value': 2},
      {'name': 'Fairmont Street', 'value': 2},
      {'name': 'Florence Street', 'value': 2},
      {'name': 'Foster Street', 'value': 2},
      {'name': 'Grozier Road', 'value': 2},
      {'name': 'Hayes Street', 'value': 2},
      {'name': 'Jay Street', 'value': 2},
      {'name': 'Lambert Street', 'value': 2},
      {'name': 'Lawn Street', 'value': 2},
      {'name': 'Museum Way', 'value': 2},
      {'name': 'Putnam Avenue', 'value': 2},
      {'name': 'Salem Street', 'value': 2},
      {'name': 'South Street', 'value': 2},
      {'name': 'Third Street', 'value': 2},
      {'name': 'Warwick Park', 'value': 2},
      {'name': 'Watson Street', 'value': 2},
      {'name': 'Irving Street', 'value': 2},
      {'name': 'Homer Avenue', 'value': 2},
      {'name': 'Laurel Street', 'value': 2},
      {'name': 'Donnell Street', 'value': 2},
      {'name': 'King Street', 'value': 2},
      {'name': 'Vassar Street', 'value': 2},
      {'name': 'William Street', 'value': 2},
      {'name': 'Arrow Street', 'value': 2},
      {'name': 'Pleasant Place', 'value': 2},
      {'name': '3rd Street', 'value': 2},
      {'name': 'Alewife Red Line', 'value': 2},
      {'name': 'Kinnaird Street', 'value': 2},
      {'name': 'Dewolfe Street', 'value': 2},
      {'name': 'Linden Street', 'value': 2},
      {'name': 'Palmer Street', 'value': 2},
      {'name': 'Mooney Street', 'value': 2},
      {'name': 'Industrial Park Road', 'value': 1},
      {'name': 'Buena Vista Park', 'value': 1},
      {'name': 'Newman Street', 'value': 1},
      {'name': 'Cambridgepark Drive', 'value': 1},
      {'name': 'Aberdeen Ave', 'value': 1},
      {'name': 'Linnaean Street', 'value': 1},
      {'name': 'Michael Way', 'value': 1},
      {'name': 'Bond Street', 'value': 1},
      {'name': 'Valentine Street', 'value': 1},
      {'name': 'Bent Street', 'value': 1},
      {'name': 'Cameron Ave', 'value': 1},
      {'name': 'George Street', 'value': 1},
      {'name': 'Sherman Street', 'value': 1},
      {'name': 'Third Streets', 'value': 1},
      {'name': 'Cornelius Way', 'value': 1},
      {'name': 'Hubbard Avenue', 'value': 1},
      {'name': 'Vincent Street', 'value': 1},
      {'name': 'Hastings Square', 'value': 1},
      {'name': 'Lopez Street', 'value': 1},
      {'name': 'Adams Terrace', 'value': 1},
      {'name': 'Lakeview Ave', 'value': 1},
      {'name': 'Lexington Street', 'value': 1},
      {'name': 'Worcester Street', 'value': 1},
      {'name': 'Galileo Way', 'value': 1},
      {'name': 'Jefferson St', 'value': 1},
      {'name': 'Norfolk St', 'value': 1},
      {'name': 'West Service Drive', 'value': 1},
      {'name': 'Willow Street', 'value': 1},
      {'name': 'Albany Street', 'value': 1},
      {'name': 'Alewife Brook Pkwy', 'value': 1},
      {'name': 'Ashburton Place', 'value': 1},
      {'name': 'Austin Park', 'value': 1},
      {'name': 'Brown Street', 'value': 1},
      {'name': 'Channing Circle', 'value': 1},
      {'name': 'Clark Street', 'value': 1},
      {'name': 'Cottage Court', 'value': 1},
      {'name': 'Crescent Street', 'value': 1},
      {'name': 'Fairfield Street', 'value': 1},
      {'name': 'Fawcett Street', 'value': 1},
      {'name': 'Garfield Street', 'value': 1},
      {'name': 'Gerry Street', 'value': 1},
      {'name': 'Hamilton Street', 'value': 1},
      {'name': 'High Street', 'value': 1},
      {'name': 'Hollis Street', 'value': 1},
      {'name': 'Humboldt Street', 'value': 1},
      {'name': 'Kimball Lane', 'value': 1},
      {'name': 'Larchwood Drive', 'value': 1},
      {'name': 'Lee Street', 'value': 1},
      {'name': 'Lincoln Street', 'value': 1},
      {'name': 'Lopez Avenue', 'value': 1},
      {'name': 'Meacham Road', 'value': 1},
      {'name': 'Milton Street', 'value': 1},
      {'name': 'Reed Street', 'value': 1},
      {'name': 'Reservoir Street', 'value': 1},
      {'name': 'Rice Street', 'value': 1},
      {'name': 'Riverside Place', 'value': 1},
      {'name': 'Roberts Road', 'value': 1},
      {'name': 'Royal Avenue', 'value': 1},
      {'name': 'Russell Street', 'value': 1},
      {'name': 'Soden Place', 'value': 1},
      {'name': 'Terminal Road', 'value': 1},
      {'name': 'Warren Street', 'value': 1},
      {'name': 'White Street', 'value': 1},
      {'name': 'Willard Street', 'value': 1},
      {'name': 'Chauncy Street', 'value': 1},
      {'name': 'Chilton Street', 'value': 1},
      {'name': 'Clinton Street', 'value': 1},
      {'name': 'Doane Street', 'value': 1},
      {'name': 'Dudley Court', 'value': 1},
      {'name': 'Glenwood Avenue', 'value': 1},
      {'name': 'Jackson Gardens', 'value': 1},
      {'name': 'Kenwood Street', 'value': 1},
      {'name': 'Lancaster Street', 'value': 1},
      {'name': 'Lincoln Way', 'value': 1},
      {'name': 'Locust Street', 'value': 1},
      {'name': 'Lowell Street', 'value': 1},
      {'name': 'McTernan Street', 'value': 1},
      {'name': 'Normandy Avenue', 'value': 1},
      {'name': 'Notre Dame Avenue', 'value': 1},
      {'name': 'Oakland Street', 'value': 1},
      {'name': 'Scouting Way', 'value': 1},
      {'name': 'Shady Hill Square', 'value': 1},
      {'name': 'Speridakis Terrace', 'value': 1},
      {'name': 'Temple Street', 'value': 1},
      {'name': 'Tremont Street', 'value': 1},
      {'name': 'Trowbridge Street', 'value': 1},
      {'name': 'Waverly Street', 'value': 1},
      {'name': 'Wendell Street', 'value': 1},
      {'name': 'Whittier Street', 'value': 1},
      {'name': 'Winslow Street', 'value': 1},
      {'name': 'Wood Street', 'value': 1},
      {'name': 'Avon Hill Street', 'value': 1},
      {'name': 'Ellery Street', 'value': 1},
      {'name': 'Ellsworth Avenue', 'value': 1},
      {'name': 'Felton Street', 'value': 1},
      {'name': 'Hovey street', 'value': 1},
      {'name': 'Trowbridge', 'value': 1},
      {'name': 'Whittemore Avenue', 'value': 1},
      {'name': '6th Street', 'value': 1},
      {'name': 'Centre Street', 'value': 1},
      {'name': 'Douglas Street', 'value': 1},
      {'name': 'Gerrys Landing Road', 'value': 1},
      {'name': 'Thorndike Way', 'value': 1},
      {'name': 'Kendall Street', 'value': 1},
      {'name': 'Lake View Avenue', 'value': 1},
      {'name': 'Saint Paul Street', 'value': 1},
      {'name': 'Arcadia Street', 'value': 1},
      {'name': 'Blackstone street', 'value': 1},
      {'name': 'Harris Street', 'value': 1},
      {'name': 'Carleton Street', 'value': 1},
      {'name': 'Arnold Circle', 'value': 1},
      {'name': 'Brookford Street', 'value': 1},
      {'name': 'Bennett Street', 'value': 1},
      {'name': 'Cardinal Medeiros Avenue', 'value': 1},
      {'name': 'Dock Street', 'value': 1},
      {'name': 'Eliot Square', 'value': 1},
      {'name': 'Farwell Place', 'value': 1},
      {'name': 'Hilliard Street', 'value': 1},
      {'name': 'Holyoke Place', 'value': 1},
      {'name': 'Mifflin Place', 'value': 1},
      {'name': 'Murdock Street', 'value': 1},
      {'name': 'Seven Pines Avenue', 'value': 1},
      {'name': 'University Road', 'value': 1},
      {'name': 'Allen Street', 'value': 1},
      {'name': 'Cameron Avenue', 'value': 1},
      {'name': 'Cottage Park Avenue', 'value': 1},
      {'name': 'Cross Street', 'value': 1},
      {'name': 'Day Street', 'value': 1},
      {'name': 'Essex Street', 'value': 1},
      {'name': 'Hews Street', 'value': 1},
      {'name': 'Loomis Street', 'value': 1},
      {'name': 'Magoun Street', 'value': 1},
      {'name': 'Park Avenue', 'value': 1},
      {'name': 'Ross Street', 'value': 1},
      {'name': 'Smith Place', 'value': 1},
      {'name': 'Wheeler Street', 'value': 1},
      {'name': 'Hammond Street', 'value': 1},
      {'name': 'Washburn Avenue', 'value': 1},
      {'name': 'Galileo Galilei Way', 'value': 1},
      {'name': 'Land Boulevard', 'value': 1},
      {'name': 'Lechmere Square', 'value': 1}
      ]
      },
      {
      name: "planning board",
      children: [
      {'name': 'Broadway', 'value': 2},
      {'name': 'Cambridge Street', 'value': 2},
      {'name': 'Cambridge Park Drive', 'value': 1},
      {'name': 'Central Square', 'value': 1},
      {'name': 'Chilton Street', 'value': 1},
      {'name': 'Columbia Street', 'value': 1},
      {'name': 'Garden Street', 'value': 1},
      {'name': 'Hampshire Street', 'value': 1},
      {'name': 'Hollis Street', 'value': 1},
      {'name': 'Kendall Square', 'value': 1},
      {'name': 'King Open', 'value': 1},
      {'name': 'Lincoln Street', 'value': 1},
      {'name': 'Massachusetts Avenue', 'value': 1},
      {'name': 'Montague', 'value': 1},
      {'name': 'Norfolk Street', 'value': 1},
      {'name': 'Palermo Street', 'value': 1},
      {'name': 'South Street', 'value': 1},
      {'name': 'Spring Hill', 'value': 1},
      {'name': 'Storrow Drive', 'value': 1},
      {'name': 'Trowbridge Street', 'value': 1},
      {'name': 'Webster Avenue', 'value': 1},
      {'name': 'Western Avenue', 'value': 1},
      {'name': 'Willow Street', 'value': 1},
      {'name': 'Windsor Street', 'value': 1},
      {'name': 'Church Street', 'value': 1},
      {'name': 'Creighton Street', 'value': 1},
      {'name': 'Dana Street', 'value': 1},
      {'name': 'Regent Street', 'value': 1},
      {'name': 'Thorndike Street', 'value': 1},
      {'name': 'Walden Street', 'value': 1}
      ]
      },
      {
      name: "Neighborhood & Long Term Planning, Public Facilities, Arts & Celebration Committee Committee Meeting",
      children: [
      {'name': 'Hurley Street', 'value': 1}
      ]
      },
      {
      name: "Public Safety Committee Committee Meeting",
      children: [
      {'name': 'Cedar Street', 'value': 1},
      {'name': 'Spring Street', 'value': 1},
      {'name': 'Windsor Street', 'value': 1},
      {'name': 'Cottage Street', 'value': 1}
      ]
      },
      {
      name: "Planning Board Planning Board Meeting",
      children: [
      {'name': 'Central Square', 'value': 19},
      {'name': 'Massachusetts Avenue', 'value': 17},
      {'name': 'Broadway', 'value': 12},
      {'name': 'Hurley Street', 'value': 11},
      {'name': 'Binney Street', 'value': 10},
      {'name': 'Cambridge Street', 'value': 10},
      {'name': 'Mass Avenue', 'value': 10},
      {'name': 'Porter Square', 'value': 9},
      {'name': 'Main Street', 'value': 8},
      {'name': 'Cambridge Park Drive', 'value': 7},
      {'name': 'Smith Place', 'value': 7},
      {'name': 'Kendall Square', 'value': 7},
      {'name': 'Harvard Square', 'value': 6},
      {'name': 'Mount Auburn Street', 'value': 6},
      {'name': 'Creighton Street', 'value': 6},
      {'name': 'New Street', 'value': 6},
      {'name': 'Concord Avenue', 'value': 5},
      {'name': 'Loomis Street', 'value': 4},
      {'name': 'Fawcett Street', 'value': 4},
      {'name': 'Green Street', 'value': 4},
      {'name': 'Harvard Street', 'value': 4},
      {'name': 'Rogers Street', 'value': 4},
      {'name': 'Fulkerson Street', 'value': 4},
      {'name': 'Laurel Street', 'value': 4},
      {'name': 'Thorndike Street', 'value': 4},
      {'name': 'Hampshire Street', 'value': 4},
      {'name': 'Cambridgeside Place', 'value': 3},
      {'name': 'James Way', 'value': 3},
      {'name': 'Auburn Street', 'value': 3},
      {'name': 'Ames Street', 'value': 3},
      {'name': 'Memorial Drive', 'value': 3},
      {'name': 'Spring Street', 'value': 3},
      {'name': 'Brattle Street', 'value': 3},
      {'name': 'Wheeler Street', 'value': 3},
      {'name': 'Seven Pines Avenue', 'value': 3},
      {'name': 'Walden Street', 'value': 3},
      {'name': 'King Street', 'value': 3},
      {'name': 'Norfolk Street', 'value': 3},
      {'name': 'Mt. Auburn Street', 'value': 3},
      {'name': 'Inman Square', 'value': 2},
      {'name': 'Rindge Avenue', 'value': 2},
      {'name': 'Concord Ave', 'value': 2},
      {'name': 'Elm Street', 'value': 2},
      {'name': 'Franklin Street', 'value': 2},
      {'name': 'Canal Park', 'value': 2},
      {'name': 'Charles Park', 'value': 2},
      {'name': 'Land Boulevard', 'value': 2},
      {'name': 'Vassar Street', 'value': 2},
      {'name': 'Wadsworth Street', 'value': 2},
      {'name': 'Otis Street', 'value': 2},
      {'name': 'Third Street', 'value': 2},
      {'name': 'Upland Road', 'value': 2},
      {'name': 'Western Avenue', 'value': 2},
      {'name': 'Bow Street', 'value': 2},
      {'name': 'Wilson Road', 'value': 2},
      {'name': 'Summer Street', 'value': 2},
      {'name': 'Charles Street', 'value': 2},
      {'name': 'Cornelius Way', 'value': 2},
      {'name': 'Davis Square', 'value': 2},
      {'name': 'Norris Street', 'value': 2},
      {'name': 'Pemberton Street', 'value': 2},
      {'name': 'Temple Street', 'value': 2},
      {'name': 'Forest Street', 'value': 2},
      {'name': 'Grove Street', 'value': 2},
      {'name': 'Holworthy Street', 'value': 2},
      {'name': 'Orchard Street', 'value': 2},
      {'name': 'Columbia Street', 'value': 2},
      {'name': 'Garden Street', 'value': 2},
      {'name': 'Pleasant Street', 'value': 2},
      {'name': 'Prospect Street', 'value': 2},
      {'name': 'Regent Street', 'value': 2},
      {'name': 'Foster Street', 'value': 1},
      {'name': 'Salem Street', 'value': 1},
      {'name': 'Bowdoin Street', 'value': 1},
      {'name': 'Wright Street', 'value': 1},
      {'name': 'Cross Street', 'value': 1},
      {'name': 'Essex Street', 'value': 1},
      {'name': 'Griswold Street', 'value': 1},
      {'name': 'Madison Avenue', 'value': 1},
      {'name': 'Magazine Street', 'value': 1},
      {'name': 'Mooney Street', 'value': 1},
      {'name': 'Ross Street', 'value': 1},
      {'name': 'Amherst Street', 'value': 1},
      {'name': 'Dock Street', 'value': 1},
      {'name': 'Hayward Street', 'value': 1},
      {'name': 'Reed Street', 'value': 1},
      {'name': 'Thorndike Way', 'value': 1},
      {'name': 'Bent Street', 'value': 1},
      {'name': 'Porter Road', 'value': 1},
      {'name': 'Appian Way', 'value': 1},
      {'name': 'Dunster Street', 'value': 1},
      {'name': 'Cardinal Medeiros Avenue', 'value': 1},
      {'name': 'Inman Street', 'value': 1},
      {'name': 'Galileo Way', 'value': 1},
      {'name': 'Michael Way', 'value': 1},
      {'name': 'Washington Avenue', 'value': 1},
      {'name': 'Alberta Terrace', 'value': 1},
      {'name': 'Cogswell Avenue', 'value': 1},
      {'name': 'Frost Terrace', 'value': 1},
      {'name': 'Richdale Avenue', 'value': 1},
      {'name': 'Blake Street', 'value': 1},
      {'name': 'George Street', 'value': 1},
      {'name': 'School Street', 'value': 1},
      {'name': 'Tremont Street', 'value': 1},
      {'name': 'Clinton Street', 'value': 1},
      {'name': 'Cottage Street', 'value': 1},
      {'name': 'Market Street', 'value': 1},
      {'name': 'Portland Street', 'value': 1},
      {'name': 'Sidney Street', 'value': 1},
      {'name': 'Galileo Street', 'value': 1},
      {'name': 'Walnut Avenue', 'value': 1},
      {'name': 'Acorn Street', 'value': 1},
      {'name': 'Antrim Street', 'value': 1},
      {'name': 'Blanchard Road', 'value': 1},
      {'name': 'Cherry Street', 'value': 1},
      {'name': 'Corporal Burns Road', 'value': 1},
      {'name': 'Irving Street', 'value': 1},
      {'name': 'Jefferson Park', 'value': 1},
      {'name': 'Notre Dame Avenue', 'value': 1},
      {'name': 'Pine Street', 'value': 1},
      {'name': 'Bishop Allen Street', 'value': 1},
      {'name': 'Chilton Street', 'value': 1},
      {'name': 'Hollis Street', 'value': 1},
      {'name': 'King Open', 'value': 1},
      {'name': 'Lincoln Street', 'value': 1},
      {'name': 'Montague', 'value': 1},
      {'name': 'Palermo Street', 'value': 1},
      {'name': 'South Street', 'value': 1},
      {'name': 'Spring Hill', 'value': 1},
      {'name': 'Storrow Drive', 'value': 1},
      {'name': 'Trowbridge', 'value': 1},
      {'name': 'Trowbridge Street', 'value': 1},
      {'name': 'Webster Avenue', 'value': 1},
      {'name': 'Willow Street', 'value': 1},
      {'name': 'Windsor Street', 'value': 1},
      {'name': 'Linnaean Street', 'value': 1},
      {'name': 'Sciarappa Street', 'value': 1},
      {'name': 'Bigelow Street', 'value': 1},
      {'name': 'Munroe Street', 'value': 1},
      {'name': 'Potter Street', 'value': 1},
      {'name': 'Jackson Place', 'value': 1},
      {'name': 'Winthrop Street', 'value': 1},
      {'name': 'Belmont Street', 'value': 1},
      {'name': 'Bishop Allen Drive', 'value': 1},
      {'name': 'Brookline Place', 'value': 1},
      {'name': 'Fairview Avenue', 'value': 1},
      {'name': 'Granite Street', 'value': 1},
      {'name': 'Lawn Street', 'value': 1},
      {'name': 'Spruce Avenue', 'value': 1},
      {'name': 'Pleasant Place', 'value': 1},
      {'name': 'Bristol Street', 'value': 1},
      {'name': 'Winter Street', 'value': 1},
      {'name': 'Church Street', 'value': 1},
      {'name': 'Dana Street', 'value': 1},
      {'name': 'Gore Street', 'value': 1},
      {'name': 'Moulton Street', 'value': 1},
      {'name': 'Terminal Road', 'value': 1}
      ]
      },
      {
      name: "Government Operations, Rules & Claims Committee Committee Meeting",
      children: [
      {'name': 'Hurley Street', 'value': 4},
      {'name': 'Antrim Street', 'value': 2},
      {'name': 'Berkshire Street', 'value': 2},
      {'name': 'Laurel Street', 'value': 2},
      {'name': 'Norfolk Street', 'value': 2},
      {'name': 'Spring Street', 'value': 2},
      {'name': 'Florence Street', 'value': 1},
      {'name': 'Locust Street', 'value': 1},
      {'name': 'Memorial Drive', 'value': 1},
      {'name': 'Oakland Street', 'value': 1},
      {'name': 'Portland Street', 'value': 1},
      {'name': 'Raymond Street', 'value': 1},
      {'name': 'Warwick Park', 'value': 1},
      {'name': 'Corporal Burns Road', 'value': 1},
      {'name': 'Cottage Street', 'value': 1},
      {'name': 'Franklin Street', 'value': 1},
      {'name': 'Green Street', 'value': 1},
      {'name': 'Hampshire Street', 'value': 1},
      {'name': 'Irving Street', 'value': 1},
      {'name': 'Oak Street', 'value': 1},
      {'name': 'Reed Street', 'value': 1},
      {'name': 'Vassal Lane', 'value': 1},
      {'name': 'Massachusetts Avenue', 'value': 1},
      {'name': 'Bigelow Street', 'value': 1},
      {'name': 'Central Square', 'value': 1},
      {'name': 'Chestnut Street', 'value': 1},
      {'name': 'Dudley Court', 'value': 1},
      {'name': 'Dunster Street', 'value': 1},
      {'name': 'Fawcett Street', 'value': 1},
      {'name': 'Fenno Street', 'value': 1},
      {'name': 'Harvard Yard', 'value': 1},
      {'name': 'Madison Avenue', 'value': 1},
      {'name': 'Oxford Street', 'value': 1},
      {'name': 'Pine Street', 'value': 1},
      {'name': 'Thorndike Street', 'value': 1},
      {'name': 'Winter Street', 'value': 1}
      ]
      },
      {
      name: "Human Services & Veterans Committee Committee Meeting",
      children: [
      {'name': 'Cambridgepark Drive', 'value': 1},
      {'name': 'Memorial Drive', 'value': 1}
      ]
      },
      {
      name: "Housing Committee Committee Meeting",
      children: [
      {'name': 'Cherry St', 'value': 1},
      {'name': 'Cherry Street', 'value': 1},
      {'name': 'Main Street', 'value': 1},
      {'name': 'Massachusetts Avenue', 'value': 1},
      {'name': 'Memorial Drive', 'value': 1},
      {'name': 'Hurley Street', 'value': 1},
      {'name': 'Jackson Place', 'value': 1}
      ]
      },
      {
      name: "Health & Environment Committee Committee Meeting",
      children: [
      {'name': 'Donnell Street', 'value': 1},
      {'name': 'Ellsworth Avenue', 'value': 1},
      {'name': 'Gore Street', 'value': 1},
      {'name': 'King Street', 'value': 1},
      {'name': 'Lawn Street', 'value': 1},
      {'name': 'Market Street', 'value': 1},
      {'name': 'Norfolk Street', 'value': 1},
      {'name': 'Prospect Street', 'value': 1},
      {'name': 'Western Avenue', 'value': 1}
      ]
      },
      {
      name: "Transportation & Public Utilities Committee Committee Meeting",
      children: [
      {'name': 'Harvard Square', 'value': 1},
      {'name': 'Kennedy Street', 'value': 1},
      {'name': 'Market Street', 'value': 1},
      {'name': 'Massachusetts Avenue', 'value': 1},
      {'name': 'Richdale Avenue', 'value': 1},
      {'name': 'School Street', 'value': 1}
      ]
      },
      {
      name: "Ordinance Committee Committtee Meeting",
      children: [
      {'name': 'Cambridge Street', 'value': 4},
      {'name': 'Norfolk Street', 'value': 3},
      {'name': 'Harvard Street', 'value': 3},
      {'name': 'Hurley Street', 'value': 3},
      {'name': 'Massachusetts Avenue', 'value': 3},
      {'name': 'Kendall Square', 'value': 3},
      {'name': 'Hampshire Street', 'value': 2},
      {'name': 'Homer Avenue', 'value': 2},
      {'name': 'Laurel Street', 'value': 2},
      {'name': 'Fuller Place', 'value': 2},
      {'name': 'Huron Avenue', 'value': 2},
      {'name': 'Oxford Street', 'value': 2},
      {'name': 'Plymouth Street', 'value': 2},
      {'name': 'Church Street', 'value': 2},
      {'name': 'Harvard Square', 'value': 2},
      {'name': 'Fulkerson Street', 'value': 2},
      {'name': 'Berkshire Street', 'value': 1},
      {'name': 'Centre Street', 'value': 1},
      {'name': 'Douglas Street', 'value': 1},
      {'name': 'Pleasant Place', 'value': 1},
      {'name': 'Antrim Street', 'value': 1},
      {'name': 'Bristol Street', 'value': 1},
      {'name': 'Chauncy Street', 'value': 1},
      {'name': 'Chilton Street', 'value': 1},
      {'name': 'Clinton Street', 'value': 1},
      {'name': 'Concord Avenue', 'value': 1},
      {'name': 'Cottage Street', 'value': 1},
      {'name': 'Doane Street', 'value': 1},
      {'name': 'Dudley Court', 'value': 1},
      {'name': 'Earhart Street', 'value': 1},
      {'name': 'Follen Street', 'value': 1},
      {'name': 'Glenwood Avenue', 'value': 1},
      {'name': 'Green Street', 'value': 1},
      {'name': 'Grozier Road', 'value': 1},
      {'name': 'Hancock Street', 'value': 1},
      {'name': 'Irving Street', 'value': 1},
      {'name': 'Magazine Street', 'value': 1},
      {'name': 'Museum Way', 'value': 1},
      {'name': 'Notre Dame Avenue', 'value': 1},
      {'name': 'Oak Street', 'value': 1},
      {'name': 'Pine Street', 'value': 1},
      {'name': 'Speridakis Terrace', 'value': 1},
      {'name': 'Temple Street', 'value': 1},
      {'name': 'Woodrow Wilson Court', 'value': 1},
      {'name': 'Charles Street', 'value': 1},
      {'name': 'Gore Street', 'value': 1},
      {'name': 'Jackson Place', 'value': 1},
      {'name': 'Kenwood Street', 'value': 1},
      {'name': 'Normandy Avenue', 'value': 1},
      {'name': 'Pearl Street', 'value': 1},
      {'name': 'Wendell Street', 'value': 1},
      {'name': 'Winslow Street', 'value': 1},
      {'name': 'Wood Street', 'value': 1},
      {'name': 'Avon Street', 'value': 1},
      {'name': 'Arlington Street', 'value': 1},
      {'name': 'Dudley Street', 'value': 1},
      {'name': 'George Street', 'value': 1},
      {'name': 'Pemberton Street', 'value': 1},
      {'name': 'Pleasant Street', 'value': 1},
      {'name': 'Arrow Street', 'value': 1},
      {'name': 'Bow Street', 'value': 1},
      {'name': 'Brattle Street', 'value': 1},
      {'name': 'Central Square', 'value': 1},
      {'name': 'Mass Avenue', 'value': 1},
      {'name': 'Mount Auburn Street', 'value': 1},
      {'name': 'Mt. Auburn Street', 'value': 1},
      {'name': 'Porter Square', 'value': 1},
      {'name': 'Binney Street', 'value': 1},
      {'name': '3rd Street', 'value': 1},
      {'name': 'Broadway', 'value': 1},
      {'name': 'Cornelius Way', 'value': 1},
      {'name': 'Michael Way', 'value': 1},
      {'name': 'Spring Street', 'value': 1},
      {'name': 'Third Street', 'value': 1}
      ]
      },
      {
      name: "ordinace committee",
      children: [
      {'name': 'Arrow Street', 'value': 1},
      {'name': 'Auburn Street', 'value': 1},
      {'name': 'Bow Street', 'value': 1},
      {'name': 'Brattle Street', 'value': 1},
      {'name': 'Central Square', 'value': 1},
      {'name': 'Church Street', 'value': 1},
      {'name': 'Harvard Square', 'value': 1},
      {'name': 'Harvard Street', 'value': 1},
      {'name': 'Kendall Square', 'value': 1},
      {'name': 'Mass Avenue', 'value': 1},
      {'name': 'Massachusetts Avenue', 'value': 1},
      {'name': 'Mount Auburn Street', 'value': 1},
      {'name': 'Mt. Auburn Street', 'value': 1},
      {'name': 'Porter Square', 'value': 1}
      ]
      },
      {
      name: "healt environment committee",
      children: [
      {'name': 'Donnell Street', 'value': 1},
      {'name': 'Ellsworth Avenue', 'value': 1},
      {'name': 'Gore Street', 'value': 1},
      {'name': 'King Street', 'value': 1},
      {'name': 'Lawn Street', 'value': 1},
      {'name': 'Market Street', 'value': 1},
      {'name': 'Norfolk Street', 'value': 1},
      {'name': 'Prospect Street', 'value': 1},
      {'name': 'Western Avenue', 'value': 1}
      ]
      },
      {
      name: "Community Benefits Advisory Committee Working Meeting",
      children: [
      ]
      },
      {
      name: "City Council Roundtable Working Meeting",
      children: [
      {'name': 'Broadway', 'value': 1},
      {'name': 'Central Square', 'value': 1}
      ]
      }
  ]
};