# set base image (host OS)
FROM python:latest

RUN apt update && apt install -y \ 
    sox \
    pkg-config \
    libflac-dev \
    libogg-dev \
    libvorbis-dev \
    libboost-dev \
    swig \
    python3-dev

RUN git clone https://github.com/PaddlePaddle/DeepSpeech.git && \
    cd DeepSpeech

RUN apt install -y \
    build-essential \
    cmake \
    libboost-system-dev \
    libboost-thread-dev \
    libboost-program-options-dev \
    libboost-test-dev \
    libeigen3-dev \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev

RUN apt-get install -y \
    gcc-8 \
    g++-8 &&  \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 50  &&  \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 50 

RUN test -d kenlm || wget -O - https://kheafield.com/code/kenlm.tar.gz | tar xz && \
    mkdir -p kenlm/build 
RUN cd kenlm/build && cmake .. && \
    make -j4 &&  \
    make install
RUN cd kenlm &&  \
    python setup.py install && \
    touch kenlm.done 

RUN apt install -y libvorbis-dev libmp3lame-dev libmad-ocaml-dev
	
RUN test -d sox-14.4.2 || wget https://nchc.dl.sourceforge.net/project/sox/sox/14.4.2/sox-14.4.2.tar.gz && \
	tar -xvzf sox-14.4.2.tar.gz -C . && \
	cd sox-14.4.2 && ./configure --prefix=/usr/ && make -j4 && make install && \
	touch sox.done

RUN test -d soxbindings || git clone https://github.com/pseeth/soxbindings.git && \
	source venv/bin/activate; cd soxbindings && python setup.py install && \
	touch soxbindings.done

RUN cd /DeepSpeech && \ 
echo "coverage\npre-commit\npybind11\nresampy==0.2.2\nscipy==1.7.0\nsentencepiece\nsnakeviz\nSoundFile==0.9.0.post1\nsox\ntensorboardX\ntextgrid\ntypeguard\nyacs" > requirements.txt && \
    bash setup.sh

RUN pip install paddlepaddle \
    torchvision 

CMD ["mv", "DeepSpeech/", "analyze/"]
#CMD "ls && mv DeepSpeech/ analyze/"